### ISSUE TITLE
Non-Creative Flux Rift Seeds not working

### ISSUE THREAD

**Issue by alphaNumeric01** [TheCodex6824/ThaumicAugmentation#100]
Hello, 

I crafted a 1000 essentia flux rift seed as well as a few smaller ones. Even though the thaumometer is maxed out at 800 flux vs 140 or so vis, no rift spawns. I've repeated this many times with smaller flux seeds and larger ones in different areas and non of them work. I had to make a creative seed in order to get it to spawn. 

Attempting to create a rift normally after using the flux seed did not work either.

**Comment by TechnoMysterio** [comment]
A few questions to try and help clarify what might be going on: 

Firstly, where are you using flux seeds? Is it in the Overworld, the Nether or somewhere else? Are there any places where a rift might spawn above you (floating islands, mountains, above the ground if you're in a cave or something)?

Secondly, what other mods are you using and have you changed any gamerules in the world? Alternatively, are you using a specific modpack? 

Thirdly, is 'Wuss Mode' in the Thaumcraft config set to true? Because if it is, then high flux cannot create flux rifts in the world. 

And finally, what do you mean by 'attempting to create a rift normally'? Flux seeds just deposit flux into the area, so they shouldn't be any different to any other flux creation methods.

**Comment by TheCodex6824** [comment]
In addition to everything TechnoMysterio said, make sure the doDaylightCycle gamerule is set to true. Quite a few aura mechanics don't work when the world time isn't progressing (thanks Azanor), and rifts spawning might be one of them. Also, has a flux rift ever spawned in this world before?

**Comment by alphaNumeric01** [comment]
Looks like it was just Wuss mode that was messing things up. 

Sorry for the late reply, been playing this mod as well as other TC6 addons like mad. 

I do have some feedback regarding the Impetus Cannon. Do I post it here or do I make another thread?

**Comment by TechnoMysterio** [comment]
I'd suggest putting that in a new issue (also making sure to close this issue), since each issue should cover a specific topic/problem.

**Comment by alphaNumeric01** [comment]
Got it. I’ll post it in a different thread. Thanks for the help!
