### ISSUE TITLE
Discovering

### ISSUE THREAD

**Issue by slowiu06** [TheCodex6824/ThaumicAugmentation#11]
We added your awesome mod to our server, but I cannot start discovering. I had First Steps unlocked before adding this mod and maybe this is the reason. 
![2019-05-30_21 37 11](https://user-images.githubusercontent.com/7887594/58659393-1e7b4580-8323-11e9-9215-642a87099148.png)
Running a command "/thaumcraft research my_name Thaumic Augmentation" didn't helped.

**Comment by TheCodex6824** [comment]
You are correct that the reason why it's not available is because you added it after First Steps. If you want to fix it, the command you are looking for is "/thaumcraft research my_name THAUMIC_AUGMENTATION_BASE". While this _technically_ isn't my mod's fault, it probably makes sense to add a check to unlock the research if First Steps is completed but the base research isn't available.

**Comment by TheCodex6824** [comment]
Oh wow, this got fixed forever ago. Not sure how I missed this, but any version from the past year or so should be fine.
