### ISSUE TITLE
Impetus mirror doesn't link cross-dimensionally

### ISSUE THREAD

**Issue by oleg-py** [TheCodex6824/ThaumicAugmentation#123]
Thaumic Augmentation 2.0.9, Thaumcraft 6.1.BETA26.

I'm trying to link an impetus drainer in a compact machine to outside of it, which thaumonomicon says I should be able to do. When I'm placing the linked mirror, it places as unlinked one and impetus doesn't transfer through it. The links work in a same dimension (so e.g. different compact machines), but it doesn't work from End to Overworld.

Also, if broken, mirror becomes unlinked which is different from TC essentia mirror behavior.

**Comment by DoomRater** [comment]
I just tried to place one in the nether and one in the overworld and they also failed to link.  Same versions of the mods.

**Comment by TechnoMysterio** [comment]
Hmm, might be because the chunks in the other dimension aren't loaded when trying to link the mirrors (you might wanna try a chunk-loader to see if that's the case), either that or it's just that something's gone wrong with recognizing stuff cross-dimensionally. Regardless, that shouldn't really happen, so that's another problem to put on the ever-growing pile of them.

**Comment by oleg-py** [comment]
Yeah, I forgot to mention that I force-loaded chunks with FTB Utilities in all cases I've tried, even though compact machine should already keep it loaded.

**Comment by TheCodex6824** [comment]
This should be fixed in the next update. I also made the mirrors remember where they were linked if one was removed to be more in line with TC mirror behavior.

**Comment by DoomRater** [comment]
I'm using a dev build of 2.0.13 and I still can't get my mirrors to link from Overworld to Nether.  But I also don't think I've chunkloaded them either.
