### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by Carvercarver1** [TheCodex6824/ThaumicAugmentation#15]
Forge 2772 (can be 2768 for more convinience). 
Latest version of the Augmentation crashes on startup.

[crsh.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/3368733/crsh.txt)

Apparently something related to block placement/multiple block placement (spells, wards?). The rest is adressed in the comment on Curse.

**Comment by TheCodex6824** [comment]
So this mod requires the latest version of forge, but it looks like I forgot to restrict the forge version at startup so it gave a nice message instead of crashing. So all you have to do is upgrade forge. I'm going to leave this open until I add that in so it stops crashing. That being said, thank you for letting me know about this!

**Comment by Carvercarver1** [comment]
Good. Perhaps there can be a way around or crutch for it (about old fixing). I recall some modders just used the alterantive scripts for that purpose, thus making it usable on that traditional one

As for the reasons. Well, apart from server software I'm using requiring that forge, some mods I use as primary ones (one, actually) due to forge's unneded (as author says, and as I saw) render changes physically cannot update, perhaps yet. Maybe. 
If it is used above: it will lead to bizzare glitches and make it unplayable, altrough without crashing, but will cause significant issues.
