### ISSUE TITLE
[Request] Warp (and scans)

### ISSUE THREAD

**Issue by VerySaltyOreos** [TheCodex6824/ThaumicAugmentation#179]
This isn't really for your mod specifically, but you're the most active thaumcraft modder I know of and interact with.
Is there some way you could make a json hook or a script hook for adding warp to tools & armor?
For pack makers and such.
I tried using modtweaker's warp script but it did nothing. 
(It spat out an error when first trying, but after fixing the error it does nothing, just a useless line of script)
I know this isn't really your thing but I just figured I'd ask.

Also do you still plan on adding scanning to research patcher?

**Comment by TheCodex6824** [comment]
There's 2 ways to make an item have warp in TC6: either make the item itself implement an interface (which is only really good for items you are coding yourself) or add an NBT tag to the stack. The key is TC.WARP and it is a **byte** value for the warping level. I mention that because despite TC6 having an API call to add warp to an item (ThaumcraftApi.addWarpToItem), this actually only affects warp given when crafting the item, not a warping modifier on the item. I looked in the ModTweaker source and it uses the crafting the item warp, not NBT warp. So if you want to add warp to an item in that way, you need to add custom NBT with TC.WARP as the key and a byte value for the warping level.

Also yes, I do plan on updating research patcher with the scan support, I just haven't got around to it yet, sorry.

**Comment by VerySaltyOreos** [comment]
> There's 2 ways to make an item have warp in TC6: either make the item itself implement an interface (which is only really good for items you are coding yourself) or add an NBT tag to the stack. The key is TC.WARP and it is a **byte** value for the warping level. I mention that because despite TC6 having an API call to add warp to an item (ThaumcraftApi.addWarpToItem), this actually only affects warp given when crafting the item, not a warping modifier on the item. I looked in the ModTweaker source and it uses the crafting the item warp, not NBT warp. So if you want to add warp to an item in that way, you need to add custom NBT with TC.WARP as the key and a byte value for the warping level.
> 
> Also yes, I do plan on updating research patcher with the scan support, I just haven't got around to it yet, sorry.

No need to apologize, just wanted to check.
Do you know of a way to make it so items will always have an nbt tag no matter how you get it?
I've been thinking that a crafttweaker addon or something would be able to do it but idk how.

**Comment by DoomRater** [comment]
The CT documents mention creating an item using the withTag() ZenSetter in your replacement recipe.  But as for finding it in the wild, in loot, I'm not sure if you can replace the item with a tagged version of the item that smoothly.

You can see withTag() used in an already existing sample with the CraftTweaker scripts for Thaumic Wonders making the seeds for the various Thaumcraft plants renewable.  In that example, they use it to create a recipe that will convert a single item into a stack of 8, since the Infusion Matrix was never designed to create stacks of items.

**Comment by VerySaltyOreos** [comment]
> The CT documents mention creating an item using the withTag() ZenSetter in your replacement recipe. But as for finding it in the wild, in loot, I'm not sure if you can replace the item with a tagged version of the item that smoothly.
> 
> You can see withTag() used in an already existing sample with the CraftTweaker scripts for Thaumic Wonders making the seeds for the various Thaumcraft plants renewable. In that example, they use it to create a recipe that will convert a single item into a stack of 8, since the Infusion Matrix was never designed to create stacks of items.

Hey aren't you one of the people who follow me on reddit?

**Comment by DoomRater** [comment]
I'm around and active on the subreddit and I'm keeping a close eye on your work!
