### ISSUE TITLE
[Bug] Augments not working

### ISSUE THREAD

**Issue by VerySaltyOreos** [TheCodex6824/ThaumicAugmentation#183]
Wanted to see what damage difference a power augment gives, when I tried it gives me an error.
Only happens on the augmented gauntlet
https://gist.github.com/VerySaltyOreos/4dd0364e713cf3f78586d8112f5c86b9

**Comment by TheCodex6824** [comment]
That's a bit of a suspicious crash, because the only way I can see that happening is if Thaumcraft never fires an event it's supposed to. I also just tried it and it works, and I know it works for a lot of other people, so you probably have some other mod doing something weird. If you feel up to it, try the same augments with just TA + the required stuff, then if that works add back mods until it errors out again. If you don't feel like dealing with it, based on the error it looks like you will be fine if you avoid the elemental modifier.

**Comment by VerySaltyOreos** [comment]
Found the mod that causes the bug
https://gist.github.com/VerySaltyOreos/5d9bc6a5efb291c22da6f8bdde1c26bf
Thaumic speedup.
Which is weird seeing as how this is the only issue I've run into with it so far.
If you don't know how to (or just don't want to) fix it, I'll just go ahead and try to get in contact with the creator of thaumic speedup.

**Comment by TheCodex6824** [comment]
As far as I know, I'm the only person that uses the part of the Thaumcraft API that seems to have broke here, so it makes sense that this is the first time there's an issue with it. I'll look into that mod just to make sure I'm not being stupid, but assuming it's their fault I'll tell them about it.

**Comment by VerySaltyOreos** [comment]
I should mention it wasn't actually causing a crash. I have vanilla fix install that notifies me whenever the game spits out an error instead of only crashes.
