### ISSUE TITLE
[Mod Conflict] Dissolution can't determine whether some of TA's mobs are possessable

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#186]
[10:52:03] [Client thread/WARN] [Dissolution]: Could not check whether to create a possessable version of thaumicaugmentation:eldritch_warden (java.lang.NullPointerException)
[10:52:03] [Client thread/WARN] [Dissolution]: Could not check whether to create a possessable version of thaumicaugmentation:eldritch_golem (java.lang.NullPointerException)
[10:52:03] [Client thread/WARN] [Dissolution]: Could not check whether to create a possessable version of thaumicwonders:corruption_avatar (java.lang.NullPointerException)

Dissolution tries to make undead mobs possessable by Remnant players, who fly around as spirits after they die. I have no idea if there's anything you can do about this since this apparently happens during startup, and I have no idea if TA's config options for mobs that can either be undead or not have loaded.  Also I just realized I copied a section from Thaumic Wonders as well by mistake.

Also there are eldritch golems now?

Dissolution 0.3.13 and Thaumic Augmentation 2.1.2

**Comment by DoomRater** [comment]
I just realized Dissolution can't figure out whether to make the wither boss possessable for the same reason.  So I'm not entirely sure what it's looking for, but most of the mobs it can't figure out are just boss monsters.

I'll also note that this doesn't really affect anything other than not being able to possess these creatures.  I mean imagine possessing a boss monster just because it's undead.

Finally, I just realized the only monster it can't figure out that's configurable is a boss monster.  This might actually be invalid.

**Comment by TheCodex6824** [comment]
Unfortunately, Dissolution intentionally suppresses the error in this case, so figuring out exactly what the issue is becomes much more difficult. But from a quick look, I don't see anything obviously wrong that I'm doing (nor anything that would have an issue with the null world that they pass). They also seem to be doing a few steps that aren't immediately obvious to me in their purpose, so in this case you probably should ask them if this is an issue for you.
