### ISSUE TITLE
Fixing Boots of the Traveller fall distance 0 damage

### ISSUE THREAD

**Issue by Shazuli** [TheCodex6824/ThaumicAugmentation#191]
***Hi***

I can't be the only one who is annoyed by Thaumcraft's Boots of the Traveller dealing 0 damage when falling more than 3 blocks. You don't really take any damage from it, but your screen shakes and forces you to wait a bit before doing the next jump or otherwise there's a chance for you to mess it up.
You think you could a handler for fixing this? Looking at [OpenComputers' code for the Hover Boots](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/common/event/HoverBootsHandler.scala#L37) they have so the player's Y momentum is reduced by 10% each tick as long as the player hasn't fallen more than 5 blocks. Something similar to that could remove that annoying bug that did that existed in previous incarnations of Thaumcraft.

This is not for making them like the Void Thaumaturge Boots, just making so the Boots of the Traveller is more like how they behaved before and actually took damage from the player when falling more than 6 blocks, if I were to guess.

**Comment by TheCodex6824** [comment]
I'm hesitant to add general fixes like this because a content addon like Augmentation is not really the right place for them. I did make a few exceptions for things that actively hinder features of this mod (robe models not dealing with arm rotation properly) or cause mass confusion when combined with my features (void robes armor counting twice), but I don't think I want to start dumping fixes in general in here in case someone wants to make a general fix addon.

For the record though, the fix is even simpler than what you mentioned: the only reason this happens is that the *damage* events are fired after the screen shake and such is applied. There are actually separate *hurt* events that fire before it, so handling those can stop the screen shake.

Now, I thought I fixed this for the Void Thaumaturge Boots, but if I didn't then I *will* be willing to fix that.
