### ISSUE TITLE
Not right thing

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#22]
1) Aspected augmentation focuses cant be applied to gloves, if they already have augmented focus. This doesn't work even if i try to put two different augmentation focuses. Does this right?
2) Thaumnomicon says that "unforchantly, i cant apply augmentations to vanilla glove". And i was thinking, why not to make augmented glove with easy craft, same effect and ability to put in augmentations?

**Comment by TechnoMysterio** [comment]
1. Do you mean that you cannot put two Elemental Resonators (the selectable Aspect augment) onto a gauntlet? If so, then this is intended behaviour, you cannot have more than one of the same augment attached to a gauntlet. If you are confused because there are three augment slots on a gauntlet and there are only two different augments in the mod, then that's because more different types are planned.
2. There probably wouldn't be much point in making a version of the basic gauntlet that is augmentable, since Augmentation offers the two more advanced and more useful gauntlet types anyway, which would be more appealing to use, even without augments.

**Comment by shoverno2** [comment]
so...
about "2."
That's i'm talking about))

**Comment by TheCodex6824** [comment]
1. Not being able to combine 2 of the same augment is intentional - this includes multiple aspects in Elemental Resonators. The reason for this is that it would defeat the purpose of the augment by putting less of an emphasis on "choosing" an aspect to be more effective.
2. I didn't think of adding a version myself of the basic gauntlet that can be augmented, but by the time people unlock augments they already have researched the thaumium gauntlet, which is a direct upgrade from the basic gauntlet. So I don't think anyone would really want to use the basic one anymore (except *maybe* for the look, but TA gauntlets can be dyed anyway so I'm not sure even that is an issue).
