### ISSUE TITLE
Primal Cutter reports that it is a Pickaxe

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#260]
This is a fun one.  If you take a Primal Cutter, it will say that it is effective at breaking logs, wood, and leaves just fine.  But aim it at stone, and HWYLA will say you can harvest it.  Indeed, despite not being effective at breaking it, the stone will _drop cobblestone_ when mined with a Primal Cutter. I tried this in my Planet Ark pack using Thaumic Augmentation 2.1.4, and I'm pretty sure it was in there in 2.1.3 (For some reason I forgot to update it with my Mad Science pack)

I'm not sure if this is a limitation of how the tool needs to be created in order to harvest things faster or not, but I thought I'd mention it.

**Comment by TheCodex6824** [comment]
Good catch, this was another case of me wanting to make the tool like Thaumcraft but not stopping and thinking about whether it was correct or not in the first place. In this case, that means that the Primal Crusher should actually have similar behavior (although it will be much harder to spot, since most of the blocks that require the tool are pickaxe type anyway).
