### ISSUE TITLE
Crash(es) when creating world

### ISSUE THREAD

**Issue by freopt** [TheCodex6824/ThaumicAugmentation#284]
[crash-2022-05-08_14.33.50-server.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/8647566/crash-2022-05-08_14.33.50-server.txt)
[crash-2022-05-08_14.40.30-server.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/8647568/crash-2022-05-08_14.40.30-server.txt)

**Comment by freopt** [comment]
[crash-2022-05-08_14.59.50-server.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/8647613/crash-2022-05-08_14.59.50-server.txt)
and another

I've used this mod in a different custom pack and have had no problems so there must be some incompatibility

**Comment by TheCodex6824** [comment]
Something seems to be messing up the block notify event, because having either the event itself or the world be null there makes absolutely no sense. I can just add a check to make it not crash, but if you could figure out what mod causes it (don't worry about it if you can't, I know you have a big mod list) that would be great.

**Comment by freopt** [comment]
it was censoredasm replacing the event https://github.com/LoliKingdom/LoliASM/blob/4.x/src/main/java/zone/rong/loliasm/common/singletonevents/mixins/blocks/NeighborNotifyEventMixin.java

I disabled it in the config and it works now

**Comment by TheCodex6824** [comment]
I'm going to close this since it's probably not this mod's fault. That event handler in particular does actually have a subclass that is used if the coremod is disabled for the ward focus, so that might be confusing that mod a bit.
