### ISSUE TITLE
[Suggestion]  Bow of bone

### ISSUE THREAD

**Issue by Demulidor12** [TheCodex6824/ThaumicAugmentation#298]
well the bow and its special arrows are the only weapons of old thaumcraft if I'm not mistaken it didn't come to thaumcraft 6
this would bring more use for arrows

**Comment by Turkey9002** [comment]
I think I remember that being suggested before around here and there were comments about how Thaumic Wonders already added it. (Same for primal arrows) That mod hasn't been updated in a long time however and I don't think it will get any future updates.

I personally would love to see it in some fashion in augmentation but in case it's still decided against because of the reason I mentioned above there's always ideas for interesting alternatives to it like #178 for example. One other thing I never seen got mentioned before is that it could be based on Thaumcraft 2's Bow of Bone instead. :P It not only could autofire but it had shadowy particles when you fired arrows and had a chance to summon angry skeletons that fought for you when killing mobs. (In this case it would be renamed to something like 'Bow of Necropolis' to set it more apart)

For arrows having some sort of augmentable tuning vis crystal arrow would be cool. It would fit well with the mod's theme and you could augment it with any type of aspect similar to the elemental modifier augment but for bows.

**Comment by Demulidor12** [comment]
good idea
