### ISSUE TITLE
Need for cosmetic))

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#30]
I see you add cosmetic infusion. And this nice looking!)
I wonder if will be possible to morph armour. Some sort of cosmetic illusion.
Also, for now after morph armour becomes unequipmentable.

**Comment by shoverno2** [comment]
and, what about to make any item invisible. This not only cosmetic theamed, this also funny to lost your invisible item in your inventory))

**Comment by shoverno2** [comment]
The last thing - infusion TOO expensive. It should use something much cheaper. Even if this will be more essentia.

**Comment by TheCodex6824** [comment]
> Armor

I decided not to support armor on purpose - it makes things very complicated when trying to make it work properly, especially since I would also have to support normal items at the same time. Maybe I can make a special version of it that supports armor in the future.

> Invisible

I don't really see how this would be useful other than for pranking people - it just seems like a great way to lose your items. I want the morphic tool to be more of a cosmetic thing than a trolling tool.

> Expensive

I'm guessing the expensive part you're referring to is the primordial pearl - I don't know if there is anything else I can put that's "lore-friendly" enough to make sense. Throwing more essentia at it doesn't really fit either.

**Comment by shoverno2** [comment]
>Invisible

Not only for pranking, but much more for customisation. Any armor or EVEN glove(with glove that might be hard, there also focus visual). Sometimes someone want to wear only skin, keeping effects)

>Expansive

Well, maybe right way is change prim pearl to something less expansive?

**Comment by supersaiyansubtlety** [comment]
Regarding invisible items for cosmetics: 
You can just use [Cosmetic Armor Reworked](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked) and avoid confusion/item loss/etc

**Comment by TheCodex6824** [comment]
So I actually did end up adding Morphic Armor, you will see it in the next major update. I don't currently have invisible armor in, but I don't see any issue with adding it, so I'll have that ready soon as well.
