### ISSUE TITLE
[Question] Ancient focus unusable?

### ISSUE THREAD

**Issue by Kriss8089** [TheCodex6824/ThaumicAugmentation#302]
Recently I've taken down an eldritch spire, and I got a bunch of ancient focuses, a blank one included amongst the gibberish-named others. I wanted to make a healing focus out of one of them (in this case one with a spell on it already) just for experimentation, and after sitting there for five minutes, it wasn't crafted at all. I tried again with the blank ancient focus, and still no luck. Is there anything that I'm doing wrong, or are these unable to be changed?

Btw, I love this addition to thaumcraft, I've recently gotten really into it, and after playing around a lot, I'd hate to see vanilla thaumcraft without these additions.

Edit: It worked once I removed the workbench charger. I have no idea if this is how it's intended, but this seems a little strange to have it not craft within a few seconds.

**Comment by TheCodex6824** [comment]
The focal manipulator is a bit broken - I haven't found the definitive cause of the problem, but sometimes it will refuse to finish creating a focus. Anecdotally, not leaving the GUI while it is crafting seems to help, but I'm not sure if that's just luck or not. The bug seems to affect all foci, not just the TA one, but if you see it only happen with this mod's focus then that would be a bit strange.

**Comment by DoomRater** [comment]
Regarding focal manipulator, I wonder if it relates to the focal manipulator running out of vis in the aura as it is finishing?  There are only so many ways around this, and I wonder if the workbench charger makes the problem happen more often?
