### ISSUE TITLE
[Bug] Oredict for the celestial notes messes up the research minigame

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumicAugmentation#311]
When Thaumic Augmentation 2.1.7 and its dependencies are installed, ~~the theorycrafting minigame doesn't take the items damage value into account.~~ the oredictionary added by augmentation messes up the theorycrafting minigame card that asks for spesific notes.

**Comment by TheCodex6824** [comment]
Does it happen with things other than celestial notes? As part of the celestial observer, I made celestial notes have an ore dictionary entry, so that could be why those aren't working. I'm not sure about other things, because I don't think I touch the research minigame really at all (I add a few cards but I don't make any invasive changes).

**Comment by Vapaman** [comment]
> Does it happen with things other than celestial notes? As part of the celestial observer, I made celestial notes have an ore dictionary entry, so that could be why those aren't working. I'm not sure about other things, because I don't think I touch the research minigame really at all (I add a few cards but I don't make any invasive changes).

I think you might be right as I tried with this: the artiface card that asks for a empty map (minecraft:map, damage:0) cannot accept filled maps (minecraft:map, damage:1). This is also the case for anvils; card cannot accept a differing damage value.
