### ISSUE TITLE
[Bug] Celestial Observer cannot pull from a chest directly beneath it

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumicAugmentation#331]
**Installed mods**: Thaumic Augmentation 2.1.9 and its dependents

**Bug**: Celestial Observer cannot pull from vanilla chest due to the chest being smaller than one block

**Demonstration**:
![2023-03-03_00 00 02](https://user-images.githubusercontent.com/77460466/222568359-904ab86e-f0dc-4bd9-b2fc-e76df358667b.png)
Two celestial observers with different block size containers, a chest and a dispenser.

![2023-03-03_00 00 36](https://user-images.githubusercontent.com/77460466/222568400-bc5ca408-6f24-456b-b67b-231608f663d0.png)
![2023-03-03_00 00 42](https://user-images.githubusercontent.com/77460466/222568412-47279060-6052-42d6-9ebf-b1d297b83d15.png)
The first observer doesn't pull from the chest

![2023-03-03_00 00 39](https://user-images.githubusercontent.com/77460466/222568408-0be03cf6-010a-477e-9bc2-afb74c5e2bf4.png)
![2023-03-03_00 00 41](https://user-images.githubusercontent.com/77460466/222568411-85f16185-6803-4b11-8a9a-1a2c06273423.png)
The second observer does pull from the dispenser

**Comment by LincT** [comment]
Work-around:
I had a similar issue. 
I resolved it by nudging the position of the observer and having a solid block to rest it on. 
it seems it needs to be lined up just right so that it is mostly over the chest, but at full block height.
Using this method I was able to use this with double chests. 
![image](https://user-images.githubusercontent.com/11671267/223827742-4fd90120-b761-4304-9e56-657f983893be.png)
