### ISSUE TITLE
thaumic augmentation scanning as a non mod file

### ISSUE THREAD

**Issue by ipoprzreal** [TheCodex6824/ThaumicAugmentation#375]
so i downloaded the source code for the mod built it with gradle and i ran it in game only for it to not even show up or do anything i checked the debug.log to see it scanned as a non mod file how do i fix this is there a way i can force it to scan as a mod file

**Comment by TheCodex6824** [comment]
If I had to guess, it's probably missing mcmod.info in the jar. I don't know why that would happen, though. Does the mod work if you use the `runclient` gradle task (`gradlew.bat runclient`)?

If you open the jar as a zip file (rename the extension to .zip if needed - you may need to enable the windows explorer option to show file extensions), does everything in there look similar to one of the downloaded versions from CurseForge? Namely:

- Files in thecodex6824/thaumicaugmentation/* are `.class` files (or folders that contain `.class` files)
- There is an `mcmod.info` file in the top level of the jar
- There is a META-INF folder with a `.cfg` file (there will *not* be an `.EC` file like release jars, but this is expected since you're not signing the jar, which is fine)

**Comment by TheCodex6824** [comment]
Closing as this seems like a build environment issue and there is no response. If you are still seeing this, we can reopen this issue. It is worth noting we also have Github Actions builds running now, so if you just want the latest commit you can download it from the actions tab.

**Comment by ipoprzreal** [comment]
I’ll take a look at it tomorrow and see if either Mcmod.info not being
there is the issue or if it’s the build environment
