### ISSUE TITLE
[Suggestion] Summon Boss, get Primordial Pearl

### ISSUE THREAD

**Issue by katzenpapst** [TheCodex6824/ThaumicAugmentation#39]
Since it's not very likely that TC6 will be updated for 1.12 (the new team seems to focus on 1.14), I think it would be nice if another way of getting pearls besides nuking rifts would exist.

I'm not proposing something as complex as the Far Lands from previous versions. More like: craft item, summon boss, kill it, it drops a pearl.

Research: "Primal Seed"
Description: "Seeing how a Primal Pearl is being dimished when used for crafting, I wonder if the process could be reversed. Maybe I could use a similar method to growing vis crystals. Of course, such a Primal Seed would need access to the Void in order to grow. This could create additional stress on the space-time-continuum..."
Requirement: Craft and plant a Primal Seed. It's a Dangerous-level infusion of an existing primal pearl (so that you can't use it to duplicate pearls), with void seeds, amber, vacuous, perditio, vitreus.

As soon as it's planted, it creates a rift (maybe only the visual effect) right away. The rift grows, then the seed you planed explodes, the rift closes, and a boss-level Eldrich Guardian appears. It then drops a pristine Primordial Pearl.

Description part2: "I have not expected the eldrich guardians to oppose my efforts in such a way. Did my experiment endanger reality on a fundamental level, or did they just intervene to prevent me from gaining too much power? Either way, in order for such a powerful guardian to fully manifest in our reality, it must be using a primordial pearl in pristine condition. It therefore seems that my experiment to reinvigorate a primordial pearl was a success after all, even if not in the way I expected."

**Comment by TheCodex6824** [comment]
I do agree that getting pearls is far too grindy at the moment, especially after the first one when it comes down to spamming causality collapsers. The next update (whenever I actually end up finishing it, because I recently started being a full-time student again so that's sucking up a lot of my time) will probably re-add some of the TC bosses in custom dungeons, so hopefully that will be a good alternate way of getting pearls.

As for right now, I'd recommend [Thaumic Wonders](https://www.curseforge.com/minecraft/mc-mods/thaumic-wonders/files/2766547) - the latest update adds a way to grow pearls and even a boss that drops one.

I'll keep this open for now to think about it since your idea is kinda neat, but I'm probably going to stick with the dungeon idea.

**Comment by katzenpapst** [comment]
I've seen Thaumic Wonders on curseforge, but haven't quite looked into it. Since the description page is so barren, I assumed it's still very early. But I guess I should look into it now (and probably spam that author with bug reports, too, lol)

**Comment by TheCodex6824** [comment]
With the new update, there are a few bosses that can drop pearls, as well as the possibility of finding some as loot. Hopefully this helps with the grind.
