### ISSUE TITLE
Frenzy function is too aggressive(and little bit more)

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#49]
Frenzy augmentation activates potential only on damage by spell.
There's no any effect when digging, healing or doing any effect by focus.
Frenzy should have activation on cast or succsesful operation with spell

I still doesn't uderstanding, why any piece of void robe set giving double armor?
including rift strider boots

And, maybe it's imposible, but maybe you can make architecting focuses to use vis discount and "void seer area" bonus. Or, i quess, by making architecting to use those perks makes minecraft crash.

**Comment by TheCodex6824** [comment]
The intention of the frenzy modifier is to be good for continuous combat, rather than as a general bonus. Your suggestion would encourage people to spam fast-recharging foci just to get the bonus. 

As for the armor, the answer is a bit complex. There is a hidden damage reduction applied to the void armor that will *roughly* halve it with a full set, unless it is magic damage, in which case it will be less than half. However, the actual doubling of the visual armor is not related to this at all and is (probably) a bug in Thaumcraft, which I chose to replicate for consistency. I'll think about whether this was a good idea or not.

I was under the impression that Vis discounts and the wider area of the void gauntlet worked with all foci; I'll investigate this to see if I was wrong.

**Comment by shoverno2** [comment]
Now i understanding why frenzy work only in combat)

And now i understand why i was immortal when i was wearing full set))
It's quite overpowered. Even reducing armor.attribute doesn't reduce second half of void robe potential))

One time was wondering how to apply vis discount to architect effect without any conflicts. And than i realized, why it must be discount when it can be cash back. Or "vis back". Architect effect taking vis from chunk affected. Even if player staying in one chunk, vis consumes from affected chunk. Then it's almost impossible to apply vis discount to this effect. But what about to make it back for percentage amount to local aura?

**Comment by TheCodex6824** [comment]
I think the only unresolved thing here was the Void Gauntlet; it was fixed quite a bit since then, and should work perfectly now.
