### ISSUE TITLE
gauntlet voids foci  [Bug] 

### ISSUE THREAD

**Issue by olol5620** [TheCodex6824/ThaumicAugmentation#54]
Thaumic gauntlet voids foci when clearing foci (shift+f) instead of putting it back in the foci pouch.

Mod-Vers: ThaumicAugmentation-1.12.2-1.1.10
Forge-Vers: forge-1.12.2-14.23.5.2838
OS: ubuntu 18.04.1 LTS
Tested in Sever-Client env.
mod List: https://pastebin.com/eTrLLtDS

**Comment by TheCodex6824** [comment]
It works normally for me when there is room, but it seems there is a bug where it gets voided when all slots are full, instead of dropping it on the ground. Is this the same for you, or am I missing a scenario where it voids foci even when there is room for it?

**Comment by TheCodex6824** [comment]
So I did some investigation, and have found it only happens when the following is true:

1. All slots in the inventory and foci bag (if present) are full
2. A focus is being removed (shift+f), not swapped with another
3. The player must be in creative mode, otherwise the switch doesn't happen

While this isn't the end of the world as creative players can remake the foci anyway, I can't do much about this as the issue occurs on Thaumcraft's side. Any fix I could provide would be horribly invasive and open a can of worms I don't think would be wise to deal with.

I'll leave this open for a bit in case there is another scenario I missed, but I wish I could do more about it.

**Comment by olol5620** [comment]
I'll check more details, but I am playing in survival.
I will also check if it happens with the tc-vanilla-gauntlet

**Comment by olol5620** [comment]
ok, that's odd: I tried to reproduce the bug I literally encountered yesterday, but today it seems fine... 
If it happens again I will try to remember every detail

**Comment by TheCodex6824** [comment]
After some further investigation there actually is an instance where NBT data of some TA items could be voided, but I've only encountered this in creative mode so I'm not sure if it will fix what happened to you. Either way there probably will be a final 1.1 patch update to address that and some other issues as 1.2 is taking a bit longer to finish than I thought.

**Comment by TheCodex6824** [comment]
The patch update with the NBT fixes was pushed, so I'm going to close this. If it happens again to you then feel free to comment / reopen this and I'll check again.
