### ISSUE TITLE
Possible collaboration?

### ISSUE THREAD

**Issue by bt2901** [TheCodex6824/ThaumicAugmentation#56]
Hi, I'm the author of Unraveling the Eldritch, an abandoned mod for TC4 (https://github.com/bt2901/unraveling). I feel like my ideas somewhat align with yours. Would you be interested in incorporating the pyramid into the Emptiness?

**Comment by TheCodex6824** [comment]
So I took a peek at your mod ingame and you're right, we do seem to have really similar ideas. After exploring a pyramid, I can say that I feel like it could be a good fit for the mod. This is a really good time to discuss this too, as after I finished up some other things I was going to work on some worldgen/structures for the Emptiness (as it probably is a bit _too_ empty as it is). Here's my thoughts so far:

- I like the maze pyramid idea, it brings back those Outer Lands vibes without being a copy of it
- One feature I added to Thaumic Augmentation is the Ward Focus, but the way I implemented it means that blocks can be warded and still be the exact blocks they are. This means it would be easy to have the structure spawn warded so players have to actually go through it the intended way instead of breaking in.
- There are a lot of unused bosses in TC6, and I was planning on integrating some of them into a possible eldritch emptiness dungeon. My plans with that were to keep the structure warded until the boss is defeated, which will cause it to go away. The boss room would also hold something that helps set up the Impetus related content lorewise (this is still being hashed out a bit).
- I saw there were golems in traps inside, that might be a bit problematic in TC6 due to the changes to golems and them requiring placed seals to work. One thing I did add was the Autocasters from TC5, which I'm going to add an enemy eldritch variant of. They would spawn with a randomly generated focus. Would this be a good replacement?

* If you do want to experiment with the mod a bit you'll have to compile the experimental branch yourself to get the new additions like Autocasters and such. I didn't publish an alpha yet for that because I wanted to finalize mechanics first so I can write recipes and research. Everything should be mostly functional in creative though.

**Comment by bt2901** [comment]
Everything sounds really fascinating!

The overall idea behind pyramid was "imagine a powerful Thaumaturge who is a century ahead of you in research of Eldritch" (Breaking the fourth wall: maybe the Thaumaturge who was able to visit Outer Lands during previous Thaumcraft versions, before the dimension become inaccessible). The pyramid is their laboratory (abandoned or not). Golems are the guardians of this place, the giant aquarium is the spawning place for squids, etc.

Speaking of unused bosses, I'm not sure things like Eldritch Warden would fit here. Unless it's a domesticated aberration or maybe something kept in a captivity for study..? Having laboratory be abandoned and reclaimed by the Eldritch isn't out of the question either.

I think Autocasters are fine, but I would need to think about it. 

I'm OK with compiling everything myself, but I'm out of date regarding some TC 6 details and Forge APIs. Do you have any good tutorials?

**Comment by TheCodex6824** [comment]
I think I get where you were going with the idea now; in that case having Eldritch stuff be in there may not make much sense (unless it got taken over). I'll think about a way to have golems work in a TC6 context - I was worried people would just break the seal and nullify golems as a threat entirely, but there's probably a creative solution to that somewhere.

Your idea for the pyramid fits really conveniently into the plans we had for the lore though. We were actually planning on having the journal of a long-gone Thaumaturge be found in the boss room, which the player then expresses confusion at with the different (TC4) experiences documented in it. The new Impetus rift power system has some similarities to the old node system, so it would lead into the research into the advanced Impetus stuff.

As for a quick primer on TC6 and Forge - TC6 is no longer maintained (and probably never will be again) since Azanor left, so things are in a slightly rough but overall usable state there. There are a few annoying quirks as a result of its beta status but they can mostly be worked around. Forge for 1.12 is also officially no longer supported as of a few days ago, but they still seem to have [the 1.12 docs up on their website](https://mcforge.readthedocs.io/en/latest/gettingstarted/), which is a pretty good resource, especially for 1.12-specific things.

**Comment by TechnoMysterio** [comment]
Do you have a Discord account perchance? Me and Codex use Discord to discuss ideas, testing, and other assorted Thaumic Augmentation things, so if you do have an account it might be more convenient to use it in future, as it's generally a bit faster for sending messages (it's also helpful for uploading assets).

Oh, and regarding Thaumcraft 6's future, it was handed off to KingLemming for maintenance, and while he originally aimed to have it ported to versions like 1.14 or 1.15 he's been too busy to actually get started on that, so it might be a fair while before it receives any updates. Hopefully it will eventually, but at this point it's all a little unclear.

**Comment by bt2901** [comment]
Yes, I do have a Discord account, `bt#0290` (although I'm not a frequent user). I agree that discussing nitty gritty details and (possibly spoilery) lore make more sense here.

The involvement of KingLemming is another reason to prefer a different take on the endgame dungeon/boss, since we could be almost certain that unused bosses are planned to be eventually implemented.

**Comment by TechnoMysterio** [comment]
I'll send you an invite to the Thaumcraft Addon Discord server as a starting point, and from there we can use DMs or something like that so to avoid public spoilers and the like. Link: https://discord.gg/bBsBJWW

With regards to bosses, a custom boss might work well but that is also quite tricky to do. Since the mod isn't going to be updated any time soon, it will only be maintained with no new features being added (unless something changes in that regard) and definitely not on 1.12.2, they might work well enough. I agree that they might not work in what is supposed to be a pyramid-shaped Thaumaturge's base, but it's at least something to consider. It might be good to discuss this further on Discord though, spoilers and all that.

**Comment by TheCodex6824** [comment]
Given the fact that this probably isn't happening anymore, I'm going to close this. If you ever get more time / want to come back to it, let me know and I can reopen this.

(Discussing the worldgen stuff with you was still immensely helpful in increasing my understanding of what's going on and helped me to get started writing the spire generation, so you did still help quite a bit)
