### ISSUE TITLE
[BUG] Morphic tool breaks armour

### ISSUE THREAD

**Issue by Nuwbertron** [TheCodex6824/ThaumicAugmentation#65]
Mentioned this on Curse and got advised to come here.

If you attempt to morphic tool a piece of armour:
1. It becomes unequipable.
2. The apparent class of the equipment changes. When hovering over the item, chestplates look like pants and vice versa, same with helmets and boots.
3. When pressing the shift key point 2 no longer aplies. The prompt mentions the correct slot for the original (not the current appearance)

Screens:
![2020-02-26_15 09 53](https://user-images.githubusercontent.com/37812034/75349741-09c9df00-58ae-11ea-821b-2d59467fe42d.png)
![2020-02-26_15 09 58](https://user-images.githubusercontent.com/37812034/75349762-0f272980-58ae-11ea-98c3-461a8e74a2fa.png)
![2020-02-26_15 10 09](https://user-images.githubusercontent.com/37812034/75349769-12221a00-58ae-11ea-8b73-12a9a65ba179.png)
![2020-02-26_15 10 11](https://user-images.githubusercontent.com/37812034/75349777-14847400-58ae-11ea-86a9-d63e6ead24a2.png)

On Curse it was mentioned that the morphic tool's use on armour brings some griefing concerns. Personally i don't see it that way, mostly because it's use on tools has the same potential. (You can infuse a lava bucket to look like a snowball, for example.) Not going to press this any further though, this is a bug repport after all.

**Comment by TheCodex6824** [comment]
I agree with you that we're long past the point of being concerned about griefing concerns, because people can already do things like make "water buckets" that dump lava. Armor was never really intended to work with the morphic tool in the first place because the tool lacks some traits that armor needs to work. However, even if I add a proper "Morphic Armor" or something like that I fear that more complex armor might be kind of iffy. I'll try to make things work, but I also don't want to horribly break the game in the process. Either way, I probably will stop armor from being used in the morphic *tool* to stop broken behavior like that.

**Comment by Nuwbertron** [comment]
Thank you for clarifying, and thank you for trying to implement something for armour. your addon is already great and, while it would be briliant to have morphic armour, i can understand if engine limitations stop that. Thank you again for your great work so far.

**Comment by Yourname942** [comment]
Are you referring to the tool from Morph-O-Tool?
https://www.curseforge.com/minecraft/mc-mods/morph-o-tool

**Comment by TheCodex6824** [comment]
So I had a chance to look into this today. I see 2 options for how to do this:

1. Do it the same way as the Morphic Tool (the item from this mod, not to be confused with Morph-O-Tool). This has the advantage of faking the item in the inventory as well as when wearing it, with the proper faked item names and such. Most simple armor would work perfectly, but there would be an issue with armor that tries to have "set bonuses" or otherwise do item checks on armor slots. I would have to work around these on an individual basis, which means chances are high that only the Thaumium Fortress Armor and maybe Thaumic Wonders' armor would work. And by "work" in this case, I mean getting the fancy model and additional armor for wearing multiple armor pieces.
2. Keep the item the way it is, and just fake the armor model while rendering. This is probably similar to what Gadomancy did with its disguises. This would eliminate any mechanical issues with the armor as the item will not appear different to mods outside rendering. However, the item will not be changed in the inventory, nor will it have the item name of the display item (or in other words, it will look like the real item in every context except rendering on the player).

So the tl;dr for the options is that option 1 will have the proper item model and text, but may run into issues with mechanically complex armor, while option 2 has no mechanical issues but won't look convincing in places like inventories. Anyone have thoughts on which they would prefer?

**Comment by TheCodex6824** [comment]
I actually figured out how to do this with armor keeping full functionality, while also looking pretty much perfect, even in the inventory. This will make it into the next major update of the mod.
