### ISSUE TITLE
Stability Field Generator ray

### ISSUE THREAD

**Issue by SSKirillSS** [TheCodex6824/ThaumicAugmentation#75]
Simple issue: Stability Field Generator ray doesn't disappear after break this block.
![image](https://user-images.githubusercontent.com/38190325/88638109-b6112b00-d0c3-11ea-925d-a9af7861b3fb.png)
Another issue with it: Ray seems invisible after world unloading:
![image](https://user-images.githubusercontent.com/38190325/88638185-d0e39f80-d0c3-11ea-9a29-2a43f112a535.png)
If I "reactivate" SFG - ray works again

Thaumcraft-1.12.2-6.1.BETA26
ThaumicAugmentation-1.12.2-2.0.2
Mohist-1.12.2-310ebdb-server

**Comment by TechnoMysterio** [comment]
The beam remaining after breaking the device is a bug we've run into before, but it shouldn't actually do anything to the rift.

As for the Stability Field Generator not having a beam after reloading the world: that's a feature, since the device overheats when left on for long periods of time and needs to be shut off with a redstone signal for a while before it can be used again (if the device has sparks going across it, it needs to be turned off). The book has more information on the latter point, so make sure to read it carefully.

**Comment by TheCodex6824** [comment]
Beams staying after breaking it should be fixed. The beam being invisible after reloading was a result of the beam color changing not be synced to the client, so it only got updated after reloading the world. I also made the beam never go fully invisible - it will now be at least very faintly there at all times while on.
