### ISSUE TITLE
Starfield Glass variants quite expensive

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#92]
I am on the 2.0.5 version at the moment, checking out all the new things and ensuring there aren't going to be any problems should I choose to push it to my modpack.  I saw the Fortified and Starfield Glass items and that's kinda sealed it for me.  A friend of mine used to cheat to get those visions in his old Thaumaturge's Dark Castle, and now he could get them legitimately.  Only thing is the glass seems to be really expensive.  1 Starfield Glass for every stack of normal glass and 1 magical material, along with 8 sigils?  ...could we get 8 glass per crafting recipe on each step?

**Comment by TheCodex6824** [comment]
Sorry about that, it's a bug in the currently released version. The intention was to get 8 glass on each of the steps (16 for panes), but I messed up some recipe JSON so it got set to 1. I was hoping I'd have time to release a bugfix update to address that and some other things, but school has kept me so busy I haven't had much time lately. If you can compile the latest version from source it should be fixed there, otherwise you have my approval to cheat in extra glass until I release the fix ;)

On a slightly unrelated note, I also made the sigil recipe give more than 1, to line up with things like the blank seal recipe. Is that a good change?

**Comment by DoomRater** [comment]
I can compile if need be.  I've also been waiting on Roots 3.1 update, so I'm not in any rush right now to push fixes.

**Comment by TheCodex6824** [comment]
Update with the fix [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3057908)
